### ISSUE TITLE
TODO: Encryption and Decryption

### ISSUE THREAD

**Issue by ihoegen** [PasswordGeneratorandStorage/PasswordGenerator#2]
Using Java encryption and decryption libraries to store data

**Comment by mchaynes** [comment]
Idk who is going to be in charge of encryption, but this should help quite a bit.

https://docs.oracle.com/javase/7/docs/api/javax/crypto/CipherOutputStream.html

**Comment by ihoegen** [comment]
I'll do it

**Comment by ihoegen** [comment]
Completed
